name: Monthly Build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Tag
        uses: actions/github-script@v2
        id: tag
        with:
          script: |
            const now = new Date()
            return `${now.getFullYear()}${(now.getMonth() + 1).toString().padStart(2, '0')}${now.getDate().toString().padStart(2, '0')}`
          result-encoding: string
        
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install git
          sudo apt install wget
          sudo apt install python3.8
          sudo apt install python3-pip
          sudo apt install python-is-python3
          sudo apt autoremove
      
      - name: Git Clone
        run: |
          git clone https://github.com/google/OpenSK
          
      - name: Build
        run: |
          export CARGO_NET_GIT_FETCH_WITH_CLI=true
          cd ./OpenSK
          ./setup.sh
          ./deploy.py --board=nrf52840_mdk_dfu --opensk --programmer=none
          wget https://github.com/makerdiary/nrf52840-mdk-usb-dongle/raw/master/tools/uf2conv.py
          python uf2conv.py -c -f 0xada52840 -o ./target/nrf52840_mdk_dfu_merged.uf2 ./target/nrf52840_mdk_dfu_merged.hex
          
      - name: Check Hash
        run: |
          cd ./OpenSK/target
          sha1sum ./nrf52840_mdk_dfu_merged.uf2
          sha1sum ./nrf52840_mdk_dfu_merged.uf2 > ./nrf52840_mdk_dfu_merged.uf2.sha1
          md5sum ./nrf52840_mdk_dfu_merged.uf2
          md5sum ./nrf52840_mdk_dfu_merged.uf2 > ./nrf52840_mdk_dfu_merged.uf2.md5
          
      - name: Delete Older Release
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.tag.outputs.result}}
          files: |
            ./OpenSK/target/nrf52840_mdk_dfu_merged.uf2
            ./OpenSK/target/nrf52840_mdk_dfu_merged.uf2.sha1
            ./OpenSK/target/nrf52840_mdk_dfu_merged.uf2.md5
